### ISSUE TITLE
Does the current last Asternet (1.3), support .Net core 5?

### ISSUE THREAD

**Issue by Farhadesfandiar** [AsterNET/AsterNET#254]
Hi everyone, 
Before I used Asternet over .Net core 3.X and it worked well as I expected. But now I'm not sure if it supports the .netcore 5 that I'm using now? Sharing your experience is priceless.

**Comment by Farhadesfandiar** [comment]
Hi everyone, 
Before I used Asternet over .Net core 3.X and it worked well as I expected. But now I'm not sure if it supports the .netcore 5 that I'm using now? Sharing your experience is priceless.

**Comment by Deantwo** [comment]
No idea. Try it.

**Comment by jonatascalebe** [comment]
Hi FarHarDesfandiar
I builded a webapi using AsterNet, and .netCore 5 that´s worked fine. 
I published and run on my Linux Envoriment without problems.
On my case, i had to add a `System.Diagnostics.Debug` package in my dependences, but i´m not shure if will needed in your case.
Regards.

**Comment by monteirohat** [comment]
Hello.

I'm having problems with CommandResponse on Asp .Net Core with Asterisk 16. Always returns null.
`CommandAction ca = new CommandAction("sip show users");`
`var responseUsers = manager.SendAction(ca) as CommandResponse;`

I also noticed that the `determineVersion()` method in the `ManagerConnection` class cannot fetch the correct Asterisk version, due to this problem with the `CommndResponse`.

Has anyone else had this same problem?
