### ISSUE TITLE
Agents Event Missing Properties?

### ISSUE THREAD

**Issue by Akj9739** [AsterNET/AsterNET#279]
Hello,

I noticed that there is a difference in the documentation between what's here on GitHub and the SandCastle Documentation and wanted to know which version of AgentsEvent is the current documentation?

I'm trying to use the NuGet in VisualStudio which seems to match the SandCastle Doc and I wanted to be sure.

If the SandCastle Doc is the latest I'd also like to ask if the other properties in the AgentsEvent class, like Exten specifically, will be brought in or not, or what previous version had them if they were already brought in before?

**Comment by Deantwo** [comment]
I am not sure what you mean, the [`Exten` property](https://github.com/AsterNET/AsterNET/blob/c4df9d8ecb578460d6442f7cd673b9b11763fadd/Asterisk.2013/Asterisk.NET/Manager/Event/AgentsEvent.cs#L128) is in the [`AgentsEvent` class](https://github.com/AsterNET/AsterNET/blob/c4df9d8ecb578460d6442f7cd673b9b11763fadd/Asterisk.2013/Asterisk.NET/Manager/Event/AgentsEvent.cs#L8).

So what are you having issues with?

**Comment by Akj9739** [comment]
I keep getting this Error when trying to use the Exten property of AgentsEvent:

Error	CS1061	'AgentsEvent' does not contain a definition for 'Exten' and no accessible extension method 'Exten' accepting a first argument of type 'AgentsEvent' could be found (are you missing a using directive or an assembly reference?)

And my NuGet imports are this for the page:

@using AsterNET.Manager;
@using AsterNET.Manager.Event;
@using AsterNET.Manager.Action;

I was looking for what was going on and through testing the only properties my code could see were those listed in the SandCastle Documentation for AgentEvents rather than those listed here on GitHub.

**Comment by Deantwo** [comment]
> I keep getting this Error when trying to use the Exten property of AgentsEvent:
> 
> ```Error CS1061 'AgentsEvent' does not contain a definition for 'Exten' and no accessible extension method 'Exten' accepting a first argument of type 'AgentsEvent' could be found (are you missing a using directive or an assembly reference?)```

Are you sure you are referencing all the needed DLL files then? The code for that class is the same in both the NuGet and in the GitHub version, since it has not been changed since the last release. Check also .Net versions.

> I was looking for what was going on and through testing the only properties my code could see were those listed in the SandCastle Documentation for AgentEvents rather than those listed here on GitHub.

I don't know what you are trying to say with this. You already said that the documentation matches the NuGet package. And as I already said, the `Exten` property does exist in both versions of the code.

Code link: https://github.com/AsterNET/AsterNET/blob/c4df9d8ecb578460d6442f7cd673b9b11763fadd/Asterisk.2013/Asterisk.NET/Manager/Event/AgentsEvent.cs#L128
documentation link: https://asternet.github.io/AsterNET/html/Properties_T_AsterNET_Manager_Event_AgentsEvent.htm
