### ISSUE TITLE
Update on NuGet package to version 1.0.2

### ISSUE THREAD

**Issue by imanpeeman** [AsterNET/AsterNET#78]
The current NuGet package is about 1,5 years old. While I'm analyzing replacing Asterisk.NET by Asternet it would be great to have the latest version available as NuGet package 1.0.2

Thanks in advance!

**Comment by skrusty** [comment]
Agreed! Hard to find the time, but will try this weekend. Think 1.2.0 might be better version number, some new features etc, not just fixes.

**Comment by imanpeeman** [comment]
Thanks for your prompt response! Please post an update when the package will be ready! I'm in for testing :)

**Comment by imanpeeman** [comment]
Hi,

Any progress on the new package?
Thanks for the update.

Regards,

**Comment by jwmoffat** [comment]
I was also wondering about this.

@skrusty is there an existing commit you would use for the next release?  Or do you still have outstanding issues/changes you'd want to resolved first?   

I was debating pulling from source instead of NuGet as an temporary alternative; if an existing commit aligns with what you'd release, that would make it even easier for switching back later.

Also, since the last version was 1.0.1 and there are new features, why not make the next version 1.1.0 (instead of skipping it)?

**Comment by imanpeeman** [comment]
hi @skrusty,

I can imagine you're busy, but is there a small possibility for a new NuGet package for asterNet on a short term?

**Comment by skrusty** [comment]
I am going to try and do a new build today.

**Comment by imanpeeman** [comment]
Thanks! That will be awesome!

Grtz, Iman

**Comment by imanpeeman** [comment]
Hi, Any progress?

**Comment by herman1vdb** [comment]
@imanpeeman I'm currently using [my own fork](https://github.com/herman1vdb/AsterNET)'s [Nuget](https://www.nuget.org/packages/herman1vdb.AsterNet). You might want to use it until skrusty can update his. 1.0.3 = master branch 16 Feb 2017

**Comment by imanpeeman** [comment]
@herman1vdb Thanks! I'll take a look at your's.

Thanks for creating the fork / package!

**Comment by skrusty** [comment]
https://www.nuget.org/packages/AsterNET/1.2.0

Feedback and any issues welcomed as always.

Cheers
